/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int M(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int M_alloc_mem(void);
int M_init_mem(int mem);
void M_free_mem(int mem);
int M_checkout(void);
void M_release(int mem);
void M_incref(void);
void M_decref(void);
casadi_int M_n_in(void);
casadi_int M_n_out(void);
casadi_real M_default_in(casadi_int i);
const char* M_name_in(casadi_int i);
const char* M_name_out(casadi_int i);
const casadi_int* M_sparsity_in(casadi_int i);
const casadi_int* M_sparsity_out(casadi_int i);
int M_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int M_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define M_SZ_ARG 137
#define M_SZ_RES 63
#define M_SZ_IW 2540
#define M_SZ_W 27400
#ifdef __cplusplus
} /* extern "C" */
#endif
